### ISSUE TITLE
Dependency Issue: LXML has no M1 Mac Support

### ISSUE THREAD

**Issue by askpatrickw** [sgraaf/PyGPX#1]
Just an FYI for other who end up here ...
https://bugs.launchpad.net/lxml/+bug/1913032

**Comment by sgraaf** [comment]
Thanks for reporting this! I've been considering dropping lxml in favor of the builtin [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html) module. I haven't made a decision yet, but I'll keep this in mind for when I do!
